### ISSUE TITLE
Wrapper function/class for mesh-to-mesh interpolation

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#56]
The workflow uses (two) `VertexOnlyMesh`es to interpolate between meshes in parallel. It is a complex but known procedure so could be wrapped up.

**Comment by ddundo** [comment]
Hi @jwallwork23 and @stephankramer, how big of an undertaking would this be? If it's not too big and you think I could manage it, I would be happy to take this on. In my goal-based experiments one iteration of goalie's fixed_point_iteration takes about 2 hours so I'd be keen to get it running in parallel. At the moment I'm slightly worried that this "2 hours" might be a red flag in the paper, since hessian-based iteration takes about 15 minutes and yields good results.

**Comment by jwallwork23** [comment]
I haven't tried it myself but @stephankramer tells me that it has been done before. Will assign it to you but do say if you want some help. Thanks!

**Comment by jwallwork23** [comment]
I think we should achieve this by porting Goalie's interpolation functionality to Animate, once https://github.com/pyroteus/goalie/pull/128 is merged.

**Comment by ddundo** [comment]
@jwallwork23 can this be closed?
