### ISSUE TITLE
Allow mass lumping in projection

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#95]
Mass lumping the mesh-to-mesh projection operator will allow us to bound the interpolator for P1 fields.

**Comment by jwallwork23** [comment]
Blocked by #94.

**Comment by ddundo** [comment]
Thanks again for doing this @jwallwork23! Could you or @stephankramer please help me get some intuition for this? I guess it's better to ask here than on the PR for the sake of documenting it better.

I mentioned on the meeting today that I tried projecting from a 0.25km uniform mesh to itself, and computing the relative L2 error. I did that with and without lumping, with a scalar ($h$) and a vector ($u$) field - please see the figures below and their y-labels. I did the same with coarser resolution meshes, where I projected from them onto the 0.25km mesh.

Without lumping the error for the 0.25km mesh is flat at 1e-8 throughout the time interval, and a flat 1e-15 when I tried interpolating. But with lumping it's significantly larger. Is this purely due to the added numerical diffusion from lumping the mass matrix? It seems quite significant. Since it also varies in time (unlike interpolating and projection without lumping, where the error is flat), could you please help me understand when we'd expect this to be higher/lower?

Also, I guess that the error for the coarser resolution meshes is the same on the two figures because the 0.25km mesh is embedded? Could you please also help me understand again when I'd expect the projection to be more/less successful in the case of adapted meshes in the two cases (with and without lumping)?

![uniform_proj](https://github.com/mesh-adaptation/animate/assets/33790330/348226d0-aa14-4f8c-ac54-3d7cc0fb5c48)
![uniform_projLump](https://github.com/mesh-adaptation/animate/assets/33790330/6d258503-0801-49f3-beae-7387f4d2cab7)

**Comment by jwallwork23** [comment]
Pushed some work in progress to the PR. I've got as far as applying the lumping, the next step is to make the projection minimally diffusive. See (Farrell et al. 2009, eq. 35):

> To note the diffusive nature of this interpolant, consider interpolating from a mesh to itself. It is clear from Lemma 5 that the maximum is attained only if

$$ \int_\Omega\phi^k_B\mathrm{d}V = \int_\Omega \mathrm{max}q_A\phi^k_B\;\mathrm{d}V...$$
